export const products = [
	//////////////Phones//////////////

	//////////////iPhone//////////////
	{
		id: 0,
		name: 'Smartfon Apple iPhone 13 128GB - 6,1" - 12 Mpix - niebieski',
		category: 'smartphone',
		model: 'iPhone',
		price: 4499,
		cents: '00',
		image: '/src/img/iphone13.jpg',
		sale: true,
		saleAmount: 500,
		installment: 224.92,
		recomended: true,
	},
	{
		id: 1,
		name: 'Smartfon APPLE iPhone 14 128GB 5G 6.1" Północ',
		category: 'smartphone',
		model: 'iPhone',
		price: 5399,
		cents: '00',
		image: '/src/img/iphone14.jpg',
		installment: 269.95,
	},
	{
		id: 2,
		name: 'Smartfon APPLE iPhone 11 64GB 6.1" Czarny MHDA3PM/A',
		category: 'smartphone',
		model: 'iPhone',
		price: 2599,
		cents: '00',
		image: '/src/img/iphone11.jpg',
		sale: true,
		saleAmount: 250,
		installment: 129.95,
	},
	{
		id: 3,
		name: 'Smartfon APPLE iPhone 14 Pro 256GB 5G 6.1" 120Hz Złoty',
		category: 'smartphone',
		model: 'iPhone',
		price: 7599,
		cents: '00',
		image: '/src/img/iphone14-pro.jpg',
		sale: true,
		saleAmount: 1120,
		installment: 379.95,
	},
	{
		id: 4,
		name: 'Smartfon APPLE iPhone 13 mini 128GB 5G 5.4" Zielony MNFF3PM/A',
		category: 'smartphone',
		model: 'iPhone',
		price: 3999,
		cents: '00',
		image: '/src/img/iphone13-mini.jpg',
		sale: true,
		saleAmount: 400,
		installment: 199.95,
	},
	{
		id: 5,
		name: 'Smartfon APPLE iPhone 12 128GB 5G 6.1" Fioletowy MJNP3PM/A',
		category: 'smartphone',
		model: 'iPhone',
		price: 4199,
		cents: '00',
		image: '/src/img/iphone12.jpg',
		sale: true,
		saleAmount: 400,
		installment: 209.95,
	},
	//////////////Samsung//////////////
	{
		id: 6,
		name: 'Smartfon SAMSUNG Galaxy M33 6/128GB 5G 6.6" 120Hz Niebieski SM-M336BZBGEUE',
		category: 'smartphone',
		model: 'Samsung',
		price: 1599,
		cents: '00',
		image: '/src/img/galaxym33.jpg',
		sale: true,
		saleAmount: 500,
		installment: 54.95,
		recomended: true,
	},
	{
		id: 7,
		name: 'Smartfon SAMSUNG Galaxy S23 8/256GB 5G 6.1" 120Hz Czarny SM-S911',
		category: 'smartphone',
		model: 'Samsung',
		price: 4799,
		cents: '00',
		image: '/src/img/galaxys23.jpg',
		sale: true,
		saleAmount: 200,
		installment: 229.95,
	},
	{
		id: 8,
		name: 'Smartfon SAMSUNG Galaxy M23 4/128GB 5G 6.6" 120Hz Niebieski SM-M236',
		category: 'smartphone',
		model: 'Samsung',
		price: 1299,
		cents: '00',
		image: '/src/img/galaxym23.jpg',
		sale: true,
		saleAmount: 400,
		installment: 64.95,
		recomended: true,
	},
	{
		id: 9,
		name: 'Smartfon SAMSUNG Galaxy S22 8/256GB 5G 6.1" 120 Hz Czarny SM-S901',
		category: 'smartphone',
		model: 'Samsung',
		price: 3699,
		cents: '00',
		image: '/src/img/galaxys22.jpg',
		sale: true,
		saleAmount: 600,
		installment: 184.95,
		recomended: true,
	},
	{
		id: 10,
		name: 'Smartfon SAMSUNG Galaxy S20 FE 6/128GB 5G 6.5" 120Hz Niebieski SM-G781',
		category: 'smartphone',
		model: 'Samsung',
		price: 2399,
		cents: '00',
		image: '/src/img/galaxys20.jpg',
		sale: true,
		saleAmount: 200,
		installment: 119.95,
	},
	{
		id: 11,
		name: 'Smartfon SAMSUNG Galaxy A34 6/128GB 5G 6.6" 120Hz Zielony SM-A346BLGAEUE',
		category: 'smartphone',
		model: 'Samsung',
		price: 1899,
		cents: '00',
		image: '/src/img/galaxya34.jpg',
		installment: 94.95,
	},
	//////////////XIAOMI//////////////
	{
		id: 12,
		name: 'Smartfon XIAOMI Redmi Note 12 4/128GB 6.67" 120Hz Czarny',
		category: 'smartphone',
		model: 'Xiaomi',
		price: 1099,
		cents: '00',
		image: '/src/img/redminote12.jpg',
		installment: 54.95,
	},
	{
		id: 13,
		name: 'Smartfon XIAOMI Redmi Note 10 Pro 6/128GB 6.67" 120Hz Szary 31117',
		category: 'smartphone',
		model: 'Xiaomi',
		price: 1299,
		cents: '00',
		sale: true,
		saleAmount: 100,
		image: '/src/img/redminote10pro.jpg',
		installment: 64.95,
	},
	{
		id: 14,
		name: 'Smartfon XIAOMI Redmi A1 2/32GB 6.52" Czarny',
		category: 'smartphone',
		model: 'Xiaomi',
		price: 419,
		cents: '00',
		image: '/src/img/redmia1.jpg',
		installment: 20.95,
	},
	{
		id: 15,
		name: 'Smartfon XIAOMI Redmi 12C 3/32GB 6.71" Szary',
		category: 'smartphone',
		model: 'Xiaomi',
		price: 649,
		cents: '00',
		image: '/src/img/redmi12c.jpg',
		sale: true,
		saleAmount: 100,
		installment: 32.45,
	},
	{
		id: 16,
		name: 'Smartfon XIAOMI Redmi 9C 2/32GB 6.53" Szary 112',
		category: 'smartphone',
		model: 'Xiaomi',
		price: 499,
		cents: '00',
		sale: true,
		saleAmount: 80,
		image: '/src/img/redmi9c.jpg',
		installment: 20.95,
	},
	{
		id: 17,
		name: 'Smartfon XIAOMI Redmi Note 11s 6/128GB 6.43" 90Hz Niebieski',
		category: 'smartphone',
		model: 'Xiaomi',
		price: 1249,
		cents: '00',
		sale: true,
		saleAmount: 50,
		image: '/src/img/redminote11s.jpg',
		installment: 57.95,
	},
	//////////////TV//////////////

	//////////////Samsung//////////////
	{
		id: 18,
		name: 'Telewizor SAMSUNG QE55S95B 55" OLED 4K 120Hz Tizen TV Dolby Atmos HDMI 2.1',
		category: 'TV',
		model: 'Samsung',
		price: 7999,
		cents: '00',
		sale: true,
		saleAmount: 2000,
		image: '/src/img/samsungqeoled.jpg',
		installment: 299.95,
		recomended: true,
	},
	{
		id: 19,
		name: 'Telewizor SAMSUNG QE65Q77B 65" QLED 4K 120HZ Tizen TV',
		category: 'TV',
		model: 'Samsung',
		price: 5399,
		cents: '00',
		sale: true,
		saleAmount: 1500,
		image: '/src/img/samsungqeqled.jpg',
		installment: 269.95,
	},
	{
		id: 20,
		name: 'Telewizor SAMSUNG QE65Q80B 65" QLED 4K 120Hz Tizen TV Full Array Dolby Atmos HDMI 2.1',
		category: 'TV',
		model: 'Samsung',
		price: 6499,
		cents: '00',
		sale: true,
		saleAmount: 1750,
		image: '/src/img/samsungqe6.jpg',
		installment: 324.95,
	},
	{
		id: 21,
		name: 'Telewizor SAMSUNG QE65S95B 65" OLED 4K 120Hz Tizen TV Dolby Atmos HDMI 2.1',
		category: 'TV',
		model: 'Samsung',
		price: 9949,
		cents: '00',
		sale: true,
		saleAmount: 950,
		image: '/src/img/samsungqeoled.jpg',
		installment: 496.95,
	},
	{
		id: 22,
		name: 'Telewizor SAMSUNG QE32LS03TC 32" QLED Tizen TV Frame (2021)',
		category: 'TV',
		model: 'Samsung',
		price: 2178,
		cents: '00',
		sale: true,
		saleAmount: 380,
		image: '/src/img/samsungqe32.jpg',
		installment: 299.95,
	},

	//////////////Sony//////////////
	{
		id: 23,
		name: 'Telewizor SONY XR55A80JAEP 55" OLED 4K 100Hz Android TV Dolby Atmos HDMI 2.1',
		category: 'TV',
		model: 'Sony',
		price: 5699,
		cents: '00',
		sale: true,
		saleAmount: 500,
		image: '/src/img/sonyxroled.jpg',
		installment: 284.95,
	},
	{
		id: 24,
		name: 'Telewizor SONY XR-65X90K 65" LED 4K 120Hz Google TV Full Array Dolby Vision Dolby Atmos HDMI 2.1',
		category: 'TV',
		model: 'Sony',
		price: 6699,
		cents: '00',
		sale: true,
		saleAmount: 700,
		image: '/src/img/sonyxr.jpg',
		installment: 299.95,
	},
	{
		id: 25,
		name: 'Telewizor SONY KD-50X72K 50" LED 4K Android TV',
		category: 'TV',
		model: 'Sony',
		price: 3399,
		cents: '00',
		image: '/src/img/sonykd.jpg',
		installment: 169.95,
	},

	//////////////Philips//////////////
	{
		id: 26,
		name: 'Telewizor PHILIPS 65PUS8857 65" LED 4K 120Hz Android TV Ambilight x3 Dolby Atmos Dolby Vision HDMI 2.1',
		category: 'TV',
		model: 'Philips',
		price: 4499,
		cents: '00',
		image: '/src/img/philipspus.jpg',
		installment: 224.95,
	},
	{
		id: 27,
		name: 'Telewizor PHILIPS 55OLED707 55" OLED 4K 120Hz Android TV Ambilight 3 Dolby Atmos Dolby Vision HDMI 2.1',
		category: 'TV',
		model: 'Philips',
		price: 5899,
		cents: '00',
		sale: true,
		saleAmount: 700,
		image: '/src/img/philipsoled.jpg',
		installment: 294.95,
	},
	//////////////Laptopy//////////////

	//////////////Acer//////////////
	{
		id: 28,
		name: 'Laptop ACER Extensa EX215-54 15.6" i3-1115G4 8GB RAM 256GB SSD',
		category: 'laptop',
		model: 'Acer',
		price: 2199,
		cents: '00',
		sale: true,
		saleAmount: 100,
		image: '/src/img/acerextensa.jpg',
		installment: 104.95,
	},
	{
		id: 29,
		name: 'Laptop ACER Nitro 5 AN515-57 15.6" IPS 144Hz i5-11400H 16GB RAM 512GB SSD GeForce RTX3050 Windows 11 Home',
		category: 'laptop',
		model: 'Acer',
		price: 4199,
		cents: '00',
		image: '/src/img/acernitro.jpg',
		installment: 209.95,
	},
	//////////////Asus//////////////
	{
		id: 30,
		name: 'Laptop ASUS TUF Gaming F15 FX506LHB-HN359W 15.6" IPS 144Hz i5-10300H 16GB RAM 512GB SSD GeForce GTX1650 Windows 11 Home',
		category: 'laptop',
		model: 'Asus',
		price: 3899,
		cents: '00',
		image: '/src/img/asustuf.jpg',
		installment: 194.95,
	},
	//////////////Lenovo//////////////
	{
		id: 31,
		name: 'Laptop LENOVO IdeaPad Gaming 3 15IHU6 15.6" IPS i5-11320H 8GB RAM 512GB SSD GeForce RTX3050 Windows 11 Home',
		category: 'laptop',
		model: 'Lenovo',
		price: 3699,
		cents: '00',
		image: '/src/img/lenovoideapad.jpg',
		installment: 294.95,
	},

	//////////////Gry//////////////

	//////////////XBOX ONE//////////////
	{
		id: 32,
		name: 'Minecraft Starter Collection Gra XBOX ONE',
		category: 'game',
		model: 'Xbox One',
		price: 119,
		cents: '00',
		image: '/src/img/minecraftxo.jpg',
	},
	{
		id: 33,
		name: 'Red Dead Redemption 2 Gra XBOX ONE',
		category: 'game',
		model: 'Xbox One',
		price: 179,
		cents: '00',
		image: '/src/img/rdr2xo.jpg',
	},
	{
		id: 34,
		name: 'Call of Duty: Modern Warfare II Gra XBOX ONE + Steelbook',
		category: 'game',
		model: 'Xbox One',
		price: 299,
		cents: '00',
		image: '/src/img/codmw2xo.jpg',
	},

	//////////////PS4//////////////
	{
		id: 35,
		name: 'Grand Theft Auto V - Edycja Premium Gra PS4',
		category: 'game',
		model: 'PlayStation 4',
		price: 149,
		cents: '00',
		image: '/src/img/gtavps4.jpg',
	},
	{
		id: 36,
		name: 'God of War Gra PS4',
		category: 'game',
		model: 'PlayStation 4',
		price: 79,
		cents: '00',
		image: '/src/img/gowps4.jpg',
	},
	{
		id: 37,
		name: 'Assassins Creed: Valhalla Gra PS4',
		category: 'game',
		model: 'PlayStation 4',
		price: 119,
		cents: '00',
		image: '/src/img/valhalla.jpg',
	},
	{
		id: 38,
		name: 'Spider-Man Gra PS4',
		category: 'game',
		model: 'PlayStation 4',
		price: 139,
		cents: '00',
		image: '/src/img/spidermanps4.jpg',
	},
	//////////////Cameras//////////////
	//////////////gopro///////////////
	{
		id: 40,
		name: 'Kamera sportowa GOPRO HERO11 Black',
		category: 'camera',
		model: 'GOPRO',
		price: 2699,
		cents: '00',
		image: '/src/img/gopro11.jpg',
		installment: 134.95,
		recomended: true,
	},
	{
		id: 41,
		name: 'Kamera sportowa GOPRO HERO9 Black',
		category: 'camera',
		model: 'GOPRO',
		price: 1949,
		cents: '00',
		image: '/src/img/gopro9.jpg',
		installment: 97.95,
	},

	//////////////AGD//////////////
	//////////////BEKO//////////////
	{
		id: 42,
		name: 'Lodówka BEKO B3RCNA404HXB Beyond No frost 203.5cm Platynowa',
		category: 'AGD',
		model: 'Beko',
		price: 2499,
		cents: '00',
		sale: true,
		saleAmount: 100,
		image: '/src/img/beko.jpg',
		installment: 119.95,
	},
	{
		id: 43,
		name: 'Lodówka SAMSUNG RB38T774DB1 EF No frost 203cm Grafitowa',
		category: 'AGD',
		model: 'Samsung',
		price: 3399,
		cents: '00',
		sale: true,
		saleAmount: 300,
		image: '/src/img/samsungagd.jpg',
		installment: 294.95,
	},
]
